### ISSUE TITLE
AssertionError for executeTest() always saying "timeout", even if not relevant

### ISSUE THREAD

**Issue by Eric-Arellano** [ottogroup/flink-spector#38]
In `DataTestStreamBase.java`, the catch statement in `executeTest()` always prints `"Test terminated due to timeout!"` when the test has been stopped, and then appends the `AssertionError`'s message. This doesn't seem to be correct usage — the comments around the definition of `testEnv.hasBeenStopped()` say it's use is for `"e.g. timeout"`, implying the test can be stopped for more than just timeouts. 
 
--

Instead of 
```java
catch (AssertionError var2) {
            if(this.testEnv.hasBeenStopped().booleanValue()) {
                throw new AssertionError("Test terminated due timeout!" + var2.getMessage());
            } else {
                throw var2;
            }
```

Should the catch statement just be the below?
```java
catch (AssertionError var2) {
            if(this.testEnv.hasBeenStopped().booleanValue()) {
                throw new AssertionError(var2.getMessage());
            } else {
                throw var2;
            }

**Comment by lofifnc** [comment]
Your'e right! If I remember correctly there's a second scenario where the framework will stop the test manually. I think the error message should still indicate that the framework made the decision to stop the test prematurely. I have to think about if I can somehow distinguish these scenarios so the message states explicitly why the test has been terminated. I'm going to look into this during the weekend and include it in the release for Flink 1.3.1.

Cheers Alex!

**Comment by Eric-Arellano** [comment]
Great, thanks Alex for the plan to fix this!

FYI with our use case, we were getting an error because expected output was not the same as our actual Datastream. However, our message was prefixed with this warning of "terminating early due to timeout," even though it was just due to a mismatch and had nothing to due with a timeout.

**Comment by Eric-Arellano** [comment]
@lofifnc by the way, are there any ways I can help with this project? I've been looking to get involved in open source and this framework has been really useful for the project I'm currently working on.

Don't see your email on your user profile, but you can find mine on my profile.

**Comment by lofifnc** [comment]
Has been included into the new release
