### ISSUE TITLE
ExpectedRecords cannot have type Collection

### ISSUE THREAD

**Issue by Eric-Arellano** [ottogroup/flink-spector#42]
When using `List<T>` with `ExpectedRecords<T>`, a compile error returns `Incompatible equality constraint: List<T> and T`.

Example:
```java
List<Integer> integerList = new ArrayList<>();
integerList.add(1); integerList.add(2); integerList.add(3);

ExpectedRecords<List<Integer>> expectedIntegers = ExpectedRecords.create(integerList);
```

### Potential solution
I think I see why this is happening. In `org.flinkspector.core.collection`:

```java
public static <T> ExpectedRecords<T> create(Collection<T> records) {
   ExpectedRecords<T> output = new ExpectedRecords<>();
   return output.expectAll(records);
}
```

That is, when you receive a collection like above, rather than accepting that as one single record, it gets interpreted as a set of multiple records. I understand why you would want this and agree it should be kept, but I'm hoping there's a way we can also accept a Collection as just one individual record.

I'm more than happy to look into this and make a PR! I don't have a ton of experience with generics though - do any ideas immediately pop out?

@lofifnc

**Comment by Eric-Arellano** [comment]
Actually there is a workaround without having to pollute the code base or alter this `create(Collection<T>)` function!

You simply have to explicitly call the constructor, rather than using `create()`.

This works as expected:
```java
List<Integer> integerList = new ArrayList<>();
integerList.add(1); integerList.add(2); integerList.add(3);

ExpectedRecords<List<Integer>> expectedIntegers = new ExpectedRecords<>();
ExpectedRecords.expect(integerList);
```
-- 
I wasn't aware the constructor even existed. I'll add this workaround to the Wiki on section for `ExpectedRecords`.

**Comment by lofifnc** [comment]
Reopened so I can look into this myself.
