### ISSUE TITLE
Datastream test examples URL is broken

### ISSUE THREAD

**Issue by debelyoo** [ottogroup/flink-spector#53]
The following url gives a 404
https://github.com/ottogroup/flink-spector/blob/master/flinkspector-datastream/src/test/java/org/flinkspector/datastream/examples

**Comment by lofifnc** [comment]
Thanks for pointing this out. This is a side effect of renaming the project. I've updated the readme.

Here is a working url:
https://github.com/ottogroup/flink-spector/blob/master/flinkspector-datastream/src/test/java/io/flinkspector/datastream/examples
