### ISSUE TITLE
Publish versions to OSS Repository Hosting

### ISSUE THREAD

**Issue by olibye** [ottogroup/flink-spector#70]
Looks like a nice project.
Please can you publish your builds to OSSRH, otherwise it's hard to share this project amongst teams.

http://central.sonatype.org/pages/ossrh-guide.html
It's an easy process to follow, but can only really be done a repository owner.

**Comment by lofifnc** [comment]
Hi,

The project is already registered and synced with OSSRH. https://issues.sonatype.org/browse/OSSRH-33639
https://search.maven.org/#search%7Cga%7C1%7Cflinkspector
Are you experiencing troubles pulling from central?

**Comment by olibye** [comment]
Sorry, I see it now. It must have been my fat fingers.
