### ISSUE TITLE
Tests flicker when running in parallel (when using Managed State)

### ISSUE THREAD

**Issue by whipit** [ottogroup/flink-spector#72]
I am testing an operator that works on a Keyed stream and uses Managed State (e.g. ValueState, MapState).  The tests pass as expected when running them one by one - i.e. separate JUnit runs.  However, when running them in parallel, they flicker - i.e. they sometimes pass but sometimes fail.   

The 2 tests I am running are nearly identical - the only difference is they have different JUnit Test class names.  The inputs to both tests were kept constant, in my case the same JSON document.  

When I debugged the runs of both tests (run in parallel), I noticed that
1. First test passes
2. When the second test starts, it's initial state (a ValueState<T> member) **is being initialized with the last input from the first test** (this happens in the open() method of the CoProcessFunction derived class).  This is unexpected, and subsequently the test produces incorrect result stream and fails.

As I understand each DataStreamTestBase gets its own distinct test environment.  However, when using managed state there seems to be some sharing going on.  Could there be some external temporary file or socket/port re-use --- just an initial guess?

Lastly, I resorted to running the tests in separate JVMs.  This seems to fix the problem, but I still need to confirm (I _think_ I saw it still fail once - but need to double check).

(p.s. - I'll update this with a code example later today)

**Comment by whipit** [comment]
This was not an issue with the framework, but rather my understanding (or lack thereof) of the timing of events.  I'll explain here with a contrived example so others don't make the same mistake I did.

Basically, lets say I have two streams - a "Number" stream, and a "Multiplier" stream.   My CoProcessFunction accepts both these streams as input.   It keeps track (via ValueState) both the last Number it has seen as well as the last Multiplier it has seen.  Upon receiving either a Number N, if it has already seen a multiplier LM (last multiplier), then it produces a new Number with value N*LM.   Similarly, upon seeing a multiplier M, if it has already seen a number LN (last number), then it produces a new Number with value LN*M.

For example, given a Number Stream [1,] and a Multiplier Stream [10,20], the output stream should be Numbers [10, 20]....or so I thought!

But what actually happens is that for the Test that "passed", the sequence of events was -
1. Saw Number 1, stored it in LastNumberSeen.  LastMultiplierSeen is NULL, so no output.
2. Saw Multiplier 10, stored in LastMultiplierSeen.  LastNumberSeen is 1 - so output 1*10 = 10
3. Saw Multiplier 20, stored in LastMultiplierSeen.  LastNumberSeen is 1 - so output 1*20 = 20
and the output was [10, 20]

However, the test that failed, the sequence of events was
1. Saw Multiplier 10, stored in LastMultiplierSeen.  LastNumberSeen is NULL - so no output
2. Saw Multiplier 20, stored in LastMultiplierSeen.  LastNumberSeen is NULL - so no output
3. Saw Number 1, stored it in LastNumberSeen.  LastMultiplierSeen is 20, so output 1*20 = 20
and the output was [20]

My mistake was that I had an **invalid assumption** on the ordering of events between the 2 streams.

We can control the ordering on a single stream (by using EventTimeInputBuilder).   But not sure how we can control the ordering on 2 separate streams.  In reality we cannot, but for testing it would be good to have this determinism.

If you have any thoughts on that please share.  

Thanks, and sorry for the false alarm.

**Comment by whipit** [comment]
>> "But not sure how we can control the ordering on 2 separate streams. "

I was able to guarantee ordering by creating one ordered stream that contains both Number and Multiplier types (using a stream of type DataStream<Object>) - using the EventTimeBuilder.  I then filtered this stream twice - to get 2 streams one containing only Number and the other only Multiplier.  Finally, I map both those streams to produce a DataStream<Number> and DataStream<Multiplier>.

**Comment by lofifnc** [comment]
This is an interesting pattern. This issue has come up on github before but I wasn't able to come up with a solution. I think I'm going to put this in some form into the wiki.
Thanks for your writeup.

**Comment by whipit** [comment]
One oddity you may notice is that I start the EventTimeInputBuilder with an placeholder object that is a super class of both Number and Multiplier types -- in my case I just used Object().  This is to get the builder to produce a stream which can accept both types.  It gets filtered out, so a bit wasteful.
