### ISSUE TITLE
Upgrade to Flink 1.0.0

### ISSUE THREAD

**Issue by knaufk** [ottogroup/flink-spector#8]
Are there any plans on upgrading to Flink 1.0.0? I realized there is no branch yet on github.

Cheers, 

Konstantin

**Comment by lofifnc** [comment]
Hi, will definitely happen as soon as the artefacts on maven have been released.

Best,
Alex

**Comment by knaufk** [comment]
Great to hear, especially since 1.0.0 has now been released on maven central ;)

**Comment by lofifnc** [comment]
Oh man, luckily mbode beat me to it. The master branch is now working with version 1.0.0.
Feel free to check it out and report any issue's your experiencing.
