### ISSUE TITLE
Flinkspector 0.9.1 references package/classes not published by Flink

### ISSUE THREAD

**Issue by mlmitch** [ottogroup/flink-spector#88]
Part of flinkspector 0.9.1 was adding support for Flink 1.7.x.
The use of the `TestingCluster` class was introduced due to the removal of Flink's `TestBaseUtils.startCluster` (https://github.com/ottogroup/flink-spector/issues/85 and https://github.com/ottogroup/flink-spector/commit/de979a4dbaec6ed36d9c3d0a0beec2eaa90307aa).

However, it appears that `TestingCluster` and the `org.apache.flink.runtime.testingUtils` package are not distributed in Flink repos. They are in the `test` directory of `flink-runtime` (https://github.com/apache/flink/tree/release-1.7/flink-runtime/src/test/scala/org/apache/flink/runtime/testingUtils).

This results in a runtime error in `io.flinkspector.dataset.DataSetTestEnvironment.java` claiming that the `org.apache.flink.runtime.testingUtils` package does not exist.

---

A pointer to the proper usage of the 0.9.1 version would be appreciated in the case that I'm wrong.

**Comment by lofifnc** [comment]
Ok this works not as intended. I will fix this later in the day. In the meantime you can import the missing dependency yourself:

'''
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-runtime_${scala.binary.version}</artifactId>
            <version>${flink.version}</version>
            <type>test-jar</type>
        </dependency>
'''

This will import the classes in the test directory .

**Comment by mlmitch** [comment]
Thanks for the workaround!

**Comment by cslotterback** [comment]
@lofifnc the project I am working on uses sbt not maven, and we are already including the flink runtime dependency

`"org.apache.flink" % "flink-runtime_2.11" % "1.7.1"`

but this is not pulling the test classes, and when adding the Test classifier sbt faces configuration issues

> Configurations already specified for module org.apache.flink:flink-runtime_2.11:1.7.1:test

**Comment by lofifnc** [comment]
#89 should make the workaround obsolete. This has been included into release 0.9.2

**Comment by mlmitch** [comment]
Awesome. Feel free to close 👍
