### ISSUE TITLE
Is there any plan to support flink 1.8?

### ISSUE THREAD

**Issue by yunzhongniao** [ottogroup/flink-spector#91]
There are errors to run test in flink 1.8 or scala 2.12. Is there any plan to support flink 1.8 and scala 2.12.
Thanks.

**Comment by lofifnc** [comment]
On each release they are renaming the same classes again. I hope this is the case here too. So the fix should be quick.

**Comment by lofifnc** [comment]
I have been able to migrate to the new API #94. But one test keeps failing. Still working on it ...

**Comment by lofifnc** [comment]
Scala 2.12 support for 1.7 has been added in Release 0.9.3 so it will also be available for 1.8.

**Comment by yunzhongniao** [comment]
> Scala 2.12 support for 1.7 has been added in Release 0.9.3 so it will also be available for 1.8.

That works of scala 2.12 . And thanks a lot for the support. Looking forward to the new version which supports 1.8.

**Comment by lofifnc** [comment]
Version 0.9.4 with support for Flink 1.8 in combination with Scala 2.11 and 2.12 has been released. Feel free to check it out.

**Comment by yunzhongniao** [comment]
Thank you very much!
